class ClaimRecord {
  const ClaimRecord({
    required this.id,
    required this.status,
    required this.date,
    required this.amount,
    required this.description,
  });

  final String id;
  final String status;
  final String date;
  final double amount;
  final String description;

  ClaimStatus get normalizedStatus => ClaimStatusX.parse(status);

  factory ClaimRecord.fromMap(Map<String, dynamic> map) {
    final amountRaw = map['amount'] ?? map['claim_amount'] ?? map['value'];
    final dateRaw =
        map['date'] ?? map['created_at'] ?? map['submitted_at'] ?? map['time'];

    return ClaimRecord(
      id: _readString(map, <String>['id', 'claim_id'], fallback: 'CLM-0000'),
      status: _readString(map, <String>[
        'status',
        'claim_status',
      ], fallback: 'Pending'),
      date: dateRaw is String && dateRaw.trim().isNotEmpty
          ? dateRaw.trim()
          : 'Unknown date',
      amount: _toDouble(amountRaw),
      description: _readString(map, <String>[
        'description',
        'reason',
        'summary',
        'details',
      ], fallback: 'Claim was auto-generated by disruption trigger.'),
    );
  }

  static List<ClaimRecord> fallbackList() {
    return const <ClaimRecord>[
      ClaimRecord(
        id: 'CLM-1024',
        status: 'Approved',
        date: '2026-03-20',
        amount: 1200,
        description: 'Rainfall disruption payout approved automatically.',
      ),
      ClaimRecord(
        id: 'CLM-1088',
        status: 'Pending',
        date: '2026-03-27',
        amount: 850,
        description: 'Event verification in progress for payout eligibility.',
      ),
      ClaimRecord(
        id: 'CLM-1099',
        status: 'Rejected',
        date: '2026-04-01',
        amount: 0,
        description: 'Claim excluded due to non-eligible disruption window.',
      ),
    ];
  }

  static double _toDouble(dynamic value) {
    if (value is num) {
      return value.toDouble();
    }
    if (value is String) {
      return double.tryParse(value) ?? 0.0;
    }
    return 0.0;
  }

  static String _readString(
    Map<String, dynamic> source,
    List<String> keys, {
    required String fallback,
  }) {
    for (final key in keys) {
      final value = source[key];
      if (value is String && value.trim().isNotEmpty) {
        return value.trim();
      }
    }
    return fallback;
  }
}

enum ClaimStatus { approved, pending, rejected, processing, unknown }

extension ClaimStatusX on ClaimStatus {
  static ClaimStatus parse(String raw) {
    final text = raw.trim().toLowerCase();
    if (text == 'approved') {
      return ClaimStatus.approved;
    }
    if (text == 'pending') {
      return ClaimStatus.pending;
    }
    if (text == 'rejected') {
      return ClaimStatus.rejected;
    }
    if (text == 'processing') {
      return ClaimStatus.processing;
    }
    return ClaimStatus.unknown;
  }
}

class ClaimsSummary {
  const ClaimsSummary({
    required this.total,
    required this.approved,
    required this.pending,
  });

  final int total;
  final int approved;
  final int pending;

  factory ClaimsSummary.fromRecords(List<ClaimRecord> records) {
    var approvedCount = 0;
    var pendingCount = 0;

    for (final record in records) {
      final status = record.normalizedStatus;
      if (status == ClaimStatus.approved) {
        approvedCount++;
      } else if (status == ClaimStatus.pending ||
          status == ClaimStatus.processing) {
        pendingCount++;
      }
    }

    return ClaimsSummary(
      total: records.length,
      approved: approvedCount,
      pending: pendingCount,
    );
  }
}
