import 'package:carbon/core/utils/model_parsers.dart';

class ClaimRecord {
  const ClaimRecord({
    required this.id,
    required this.status,
    required this.date,
    required this.amount,
    required this.description,
  });

  final String id;
  final String status;
  final String date;
  final double amount;
  final String description;

  ClaimStatus get normalizedStatus => ClaimStatusX.parse(status);

  factory ClaimRecord.fromMap(Map<String, dynamic> map) {
    return ClaimRecord(
      id: ModelParsers.readIdentifier(
        map,
        primaryKeys: const <String>['claim_id'],
        compatibilityKeys: const <String>['id'],
        fallback: 'CLM-0000',
      ),
      status: ModelParsers.readString(
        map,
        primaryKeys: const <String>['status'],
        compatibilityKeys: const <String>['claim_status'],
        fallback: 'Pending',
      ),
      date: ModelParsers.normalizeDate(
        map['created_at'] ?? map['date'] ?? map['submitted_at'] ?? map['time'],
        fallback: 'Unknown date',
      ),
      amount: ModelParsers.readDouble(
        map,
        primaryKeys: const <String>['amount'],
        compatibilityKeys: const <String>['claim_amount', 'value'],
      ),
      description: ModelParsers.readString(
        map,
        primaryKeys: const <String>['description', 'decision_reason'],
        compatibilityKeys: const <String>['reason', 'summary', 'details'],
        fallback: 'Claim was auto-generated by disruption trigger.',
      ),
    );
  }

  static List<ClaimRecord> fallbackList() {
    if (const bool.fromEnvironment('dart.vm.product')) {
      return const <ClaimRecord>[];
    }

    return const <ClaimRecord>[
      ClaimRecord(
        id: 'CLM-1024',
        status: 'Approved',
        date: '2026-03-20',
        amount: 1200,
        description: 'Rainfall disruption payout approved automatically.',
      ),
      ClaimRecord(
        id: 'CLM-1088',
        status: 'Pending',
        date: '2026-03-27',
        amount: 850,
        description: 'Event verification in progress for payout eligibility.',
      ),
      ClaimRecord(
        id: 'CLM-1099',
        status: 'Rejected',
        date: '2026-04-01',
        amount: 0,
        description: 'Claim excluded due to non-eligible disruption window.',
      ),
    ];
  }
}

enum ClaimStatus { approved, pending, rejected, processing, unknown }

extension ClaimStatusX on ClaimStatus {
  static ClaimStatus parse(String raw) {
    final text = raw.trim().toLowerCase();
    if (text == 'approved') {
      return ClaimStatus.approved;
    }
    if (text == 'pending') {
      return ClaimStatus.pending;
    }
    if (text == 'rejected') {
      return ClaimStatus.rejected;
    }
    if (text == 'processing') {
      return ClaimStatus.processing;
    }
    return ClaimStatus.unknown;
  }
}

class ClaimsSummary {
  const ClaimsSummary({
    required this.total,
    required this.approved,
    required this.pending,
  });

  final int total;
  final int approved;
  final int pending;

  factory ClaimsSummary.fromRecords(List<ClaimRecord> records) {
    var approvedCount = 0;
    var pendingCount = 0;

    for (final record in records) {
      final status = record.normalizedStatus;
      if (status == ClaimStatus.approved) {
        approvedCount++;
      } else if (status == ClaimStatus.pending ||
          status == ClaimStatus.processing) {
        pendingCount++;
      }
    }

    return ClaimsSummary(
      total: records.length,
      approved: approvedCount,
      pending: pendingCount,
    );
  }
}
